### ISSUE TITLE
Unable to commit changes on master branch

### ISSUE THREAD

**Issue by rajpratik71** [digitallysavvy/psu-ist413-pebble-emergency-app#1]
Unable to commit changes on master branch of adding of git ignore & git attribute
 files

**Comment by digitallysavvy** [comment]
@Rajpratik71 you should not be attempting to push to master, please push to a branch or fork and create a pull request.

Since you are not a collaborator on the project you will not be able to push to any of the project's branches, so if you would like to contribute please fork the repo, commit/push your changes on the fork and then make a pull request within this repo
